export { CoffeeLogo } from './CoffeeLogo'
export { FilmLogo} from './FilmLogo'
export { FavoriteLogo} from './FavoriteLogo'
export { TrendingLogo} from './TrendingLogo'
export { CalenderLogo} from './CalenderLogo'
export { UsersLogo} from './UsersLogo'
export { CloudLogo } from './CloudLogo'
export { SlidersLogo } from './SlidersLogo'
export { LogOutLogo } from './LogOutLogo'

