export { CoffeeIcon } from './Icons/VerticalNavbar/CoffeeIcon.tsx'
export { FilmIcon} from './Icons/VerticalNavbar/FilmIcon.tsx'
export { FavoriteIcon} from './Icons/VerticalNavbar/FavoriteIcon.tsx'
export { TrendingIcon} from './Icons/VerticalNavbar/TrendingIcon.tsx'
export { CalenderIcon} from './Icons/VerticalNavbar/CalenderIcon'
export { UsersIcon} from './Icons/VerticalNavbar/UsersIcon.tsx'
export { CloudIcon } from './Icons/VerticalNavbar/CloudIcon'
export { SlidersIcon } from './Icons/VerticalNavbar/SlidersIcon.tsx'
export { LogOutIcon } from './Icons/VerticalNavbar/LogOutIcon.tsx'

